# Create a new Deployment named httpd-frontend with 3 replicas using image httpd:2.4-alpine


# k create deployment httpd-frontend --image=httpd:2.4-alpine --replicas=3
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd-frontend
  name: httpd-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-frontend
  template:
    metadata:
      labels:
        app: httpd-frontend
    spec:
      containers:
      - image: httpd:2.4-alpine
        name: httpd