# Create a Pod called sega with two containers:

#   Container 1: Name tails with image busybox and command: sleep 3600.
#   Container 2: Name sonic with image nginx and Environment variable: NGINX_PORT with the value 8080.



# Start with: k run sega --image=busybox
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sega
  name: sega
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox
    name: tails
  - image: nginx
    name: sonic
    env:
      - name: NGINX_PORT
        value: "8080"