apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort:  80
  selector:
    app: myapp
    type: back-end

# Pod al que se enlazaria
# apiVersion: v1
# kind: Pod
# metadata:
#   name: myapp-pod
#   labels:
# spec:
#   containers:
#     - name: nginx-container
#       image: nginx
  
