apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi # Siempre que se pida un tamaño igual o superior a este valor se usa este PVC
  storageClassName: manual