apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-user-rol
  namespace: dev-namespace
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list","create","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-user-binding
subjects:
  - kind: User
    name: dev-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-user-rol # campo 'name' de los metadatos creados en nuestro rol
  apiGroup: rbac.authorization.k8s.io