apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp-green
  name: webapp-green
spec:
  containers:
  - args:
    - --color
    - green
    image: kodekloud/webapp-color
    name: webapp-green
