apiVersion: apps/v1
kind: Pod
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: <name-of-my-configMap>