# Add a taint to the node node01 of the cluster. Use the specification below:
#   key: app_type, value: alpha and effect: NoSchedule

# Create a pod called alpha, image: redis with toleration to node01.

# k taint node node01 app_type=alpha:NoSchedule

# Pod:
# k run alpha --image=redis --labels=app_type=alpha
apiVersion: v1
kind: Pod
metadata:
  labels:
    app_type: alpha
  name: alpha
  namespace: default
spec:
  tolerations:
    - effect: NoSchedule
      key: app_type
      value: alpha
  containers:
  - image: redis
    name: alpha
