# Create a new Ingress Resource for the service my-video-service to be made available at: 
#       http://ckad-mock-exam-solution.com:30093/video.

# To create an ingress resource, the following details are:
#   annotation: nginx.ingress.kubernetes.io/rewrite-target: /
#   host: ckad-mock-exam-solution.com
#   path: /video

# Get services data:
# k get service
# NAME                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
# front-end-service   NodePort    172.20.182.237   <none>        80:30083/TCP   22m
# kubernetes          ClusterIP   172.20.0.1       <none>        443/TCP        43m
# my-video-service    ClusterIP   172.20.45.108    <none>        8080/TCP       9m21s


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource-backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ckad-mock-exam-solution.com
      http:
        paths:
          - path: /video
            pathType: Prefix
            backend:
              service:
                name: my-video-service #Service name
                port:
                  number: 8080 #Port of the service

# Nota: Hay un NodePort en el namesapce del ingress encargado de mapear el tráfico 80:30093.
# Por eso el curl se hace a través del 30093