# We have deployed a new pod called pod-with-rprobe.
# This Pod has an initial delay before it is Ready.
# Update the newly created pod pod-with-rprobe with a readinessProbe using the given spec

apiVersion: v1
kind: Pod
metadata:
  labels:
    name: pod-with-rprobe
  name: pod-with-rprobe
  namespace: default
spec:
  containers:
  - env:
    - name: APP_START_DELAY
      value: "180"
    image: kodekloud/webapp-delayed-start
    name: pod-with-rprobe
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe: # SECCIÓN A AGREGAR
      httpGet:
        path: /ready
        port: 8080