# Create a new pod called nginx1401 in the default namespace with the image nginx.
# Add a livenessProbe to the container to restart it if the command ls /var/www/html/probe fails.
# This check should start after a delay of 10 seconds and run every 60 seconds.

# Partiendo de: k run nginx1401 --image=nginx
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx1401
  name: nginx1401
spec:
  containers:
  - image: nginx
    name: nginx1401
    livenessProbe:
      exec:
        command:
        - ls
        - /var/www/html/probe
      initialDelaySeconds: 10
      periodSeconds: 60