# Apply a label app_type=beta to node controlplane.
# Create a new deployment called beta-apps with image: nginx and replicas: 3.
# Set Node Affinity to the deployment to place the PODs on controlplane only.

#   (NodeAffinity: requiredDuringSchedulingIgnoredDuringExecution)


# Partiendo de:
# k create deployment beta-apps --image=nginx --replicas=3
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: beta-apps
  name: beta-apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: beta-apps
  template:
    metadata:
      labels:
        app: beta-apps
    spec:
      containers:
      - image: nginx
        name: nginx
      affinity: # Agregamos la afinidad
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: app_type
                  operator: In
                  values:
                    - beta