apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteOne
  capacity:
    storage: 1Gi # El almacenamiendo que tendrá el PV
  hostPath:
    path: /tmp/data # Path loca, NO SE DEBE USAR EN PRO