apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim-name # Nombre del PVC
--- # PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim-name
spec:
  accessModes:
    - ReadWriteOne
  resources:
    requests:
      storage: 500Mi # Siempre que se pida un tamaño igual o superior a este valor se usa este PVC