apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["/bin/sh","-c"]
      args: ["shuf -i 0-100 -n 1 >> /opt/number.out;"] # Genera un nº del 1 al 100 y lo guarda en /opt/number.out
      volumeMounts: # Directorio local del pod que vive y muere junto al pod
        - mountPath: /opt # Carpeta donde se van a almacenar los ficheros. Será hija de la carperta root corespondiente
          name: data-volume
  volumes:
    - name: data-volume
      hostPath:
        path: /data #Directorio del volume que actuará de root path
        type: Directory