apiVersion: v1
kind: Job
metadata:
  name: math-job
spec:
  completions: 3 # Número de pods a lanzar, por defecto se crean de 1 en 1 SI Y SOLO SI el anterior ha terminado
  parallelism: 2
  template:
    spec:
      containers:
        - name: math-add
          image: ubuntu
          command: [ 'expr','3','+','2']
      restartPolicy: Never