apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: dev #En esta línea nos aseguramos que el recurso pertenezca siempre a ese namespace
  labels:
    tier: frontend
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp    
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
