apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  namespace: development
rules:
  # Permisos para todos los servicios del namespace development
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["*"]
  # Permisos para los persistentvolumeclaims del namespace development
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["*"]
  # Permisos para los pods del namespace development
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]