#  k run busybox-security-context --image=busybox:1.28 --command -- sh -c "sleep 1h"
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-security-context
  name: busybox-security-context
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
    - name: pod-volume
      emptyDir: {}    
  containers:
  - command:
    - sh
    - -c
    - sleep 1h
    image: busybox:1.28
    securityContext:
      allowPrivilegeEscalation: false
    name: busybox-security-context
    volumeMounts:
        - name: pod-volume
          mountPath: /data/test