apiVersion: v1
kind: Secret
metadata:
  name: db-secret
data:
  DB_Host: c3FsMDE=
  DB_Password: cGFzc3dvcmQxMjM=
  DB_User: cm9vdA==
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: redis
      image: redis
      env:
      - name: DB_Host
        valueFrom:
          secretKeyRef:
            name: db-secret #Mismo valor que 'metadata-name' del Secret
            key: DB_Host
      - name: DB_Password
        valueFrom:
          secretKeyRef:
            name: db-secret #Mismo valor que 'metadata-name' del Secret
            key: DB_Password