apiVersion: apps/v1
kind: Pod
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  containers:
    - image: kodekloud/webapp-color
      name: kodekloud/webapp-color
  volumes:
    - name: my-secret-volume
      secret:
        secretName: <name-of-my-secret>