apiVersion: apps/v1
kind: Pod
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  containers:
  - env:
    - name: <secret-name>
      valueFrom:
       secretKeyRef:
         name: <name-of-my-configMap>
         key: <name-of-env-variable>
    image: kodekloud/webapp-color
    name: webapp-color